name: CI

on:
  push:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev jest

      - name: Build project
        run: |
          npm run

      - name: Run unit tests
        run: |
          npm test

